import {describe,expect,it} from "vitest";
import {applyEditorCommands,defaultSceneElements,validateEditableProject} from "./commands";
import {createCreativeProject} from "./engine";

const fixture=()=>{const project=createCreativeProject({id:"editor-fixture",jobId:"00000000-0000-0000-0000-000000000001",projectId:"plandome",script:"Plan a loft. Review the roof. Book a call.",segments:["Plan a loft.","Review the roof.","Book a call."],durationSeconds:12,format:"portrait",quality:"preview",seed:"editor"});project.scenes.forEach(scene=>scene.elements=defaultSceneElements(project,scene.id));project.captions=[{id:"caption-1",sceneId:"scene-01",text:"Plan a loft",start:0,end:1.5,words:[]}];return project};

describe("CreativeProject editor commands",()=>{
 it("edits, moves and resizes canonical elements",()=>{const project=fixture(),id="scene-01-headline";const result=applyEditorCommands(project,[{type:"UpdateTextContent",sceneId:"scene-01",elementId:id,content:"A better loft plan"},{type:"MoveElement",sceneId:"scene-01",elementId:id,x:.12,y:.2},{type:"ResizeElement",sceneId:"scene-01",elementId:id,width:.7,height:.18}]);const element=result.project.scenes[0]!.elements!.find(item=>item.id===id)!;expect(element.content).toBe("A better loft plan");expect(element.box).toMatchObject({x:.12,y:.2,width:.7,height:.18})});
 it("updates media crop and focal point non-destructively",()=>{const project=fixture(),id="scene-01-media";const result=applyEditorCommands(project,[{type:"SetMediaCrop",sceneId:"scene-01",elementId:id,crop:{x:.1,y:.15,width:.8,height:.7}},{type:"SetMediaFocalPoint",sceneId:"scene-01",elementId:id,focalPoint:{x:.65,y:.4}}]);expect(result.project.scenes[0]!.elements![0]!.media).toMatchObject({crop:{x:.1,y:.15,width:.8,height:.7},focalPoint:{x:.65,y:.4}})});
 it("updates scene template, transition, caption, duration and order",()=>{const result=applyEditorCommands(fixture(),[{type:"ChangeSceneTemplate",sceneId:"scene-01",templateId:"luxury-property"},{type:"ChangeTransition",sceneId:"scene-01",transition:"mask-reveal"},{type:"UpdateCaption",phraseId:"caption-1",text:"Plan your loft"},{type:"ChangeSceneDuration",sceneId:"scene-01",duration:5},{type:"ReorderScene",sceneId:"scene-01",toIndex:2}]);expect(result.project.scenes[2]!.id).toBe("scene-01");expect(result.project.scenes[2]!.templateId).toBe("luxury-property");expect(result.project.captions[0]!.text).toBe("Plan your loft");expect(result.project.timeline.some(clip=>clip.track==="caption")).toBe(true)});
 it("protects locked elements",()=>{const project=fixture();project.scenes[0]!.elements!.find(e=>e.role==="headline")!.locked=true;expect(()=>applyEditorCommands(project,[{type:"MoveElement",sceneId:"scene-01",elementId:"scene-01-headline",x:.2,y:.2}])).toThrow(/locked/)});
 it("reports safe-zone and overflow findings",()=>{const project=fixture(),headline=project.scenes[0]!.elements!.find(e=>e.role==="headline")!;headline.box.x=.9;headline.content="x".repeat(150);expect(validateEditableProject(project)).toEqual(expect.arrayContaining([expect.stringMatching(/safe zone/),expect.stringMatching(/overflow/)]))});
});
