import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import { applyEditorCommands, defaultSceneElements, validateEditableProject, type CreativeProject, type EditorCommand } from "@openvideo/creative-project";
import { getVideoJob, jobDirectory } from "@/lib/video/job-store";
import { getRemoteObject, getRemoteVideoJob, putRemoteObject } from "@/lib/video/remote-store";

export const runtime="nodejs";
type Revision={id:string;version:number;createdAt:string;summary:string;project:CreativeProject;renderArtifact?:string};
const projectKey=(id:string)=>`projects/${id}.json`;
const revisionsKey=(id:string)=>`revisions/${id}.json`;
async function readProject(id:string){if(process.env.VERCEL){const value=await getRemoteObject(projectKey(id));return value?await value.json() as CreativeProject:null}try{return JSON.parse(await readFile(path.join(jobDirectory(id),"creative-project.json"),"utf8")) as CreativeProject}catch{return null}}
async function readRevisions(id:string):Promise<Revision[]>{if(process.env.VERCEL){const value=await getRemoteObject(revisionsKey(id));return value?await value.json() as Revision[]:[]}try{return JSON.parse(await readFile(path.join(jobDirectory(id),"revisions.json"),"utf8")) as Revision[]}catch{return []}}
async function save(id:string,project:CreativeProject,revisions:Revision[]){if(process.env.VERCEL){await putRemoteObject(projectKey(id),JSON.stringify(project),"application/json");await putRemoteObject(revisionsKey(id),JSON.stringify(revisions.slice(-40)),"application/json");return}await mkdir(jobDirectory(id),{recursive:true});await writeFile(path.join(jobDirectory(id),"creative-project.json"),JSON.stringify(project,null,2));await writeFile(path.join(jobDirectory(id),"revisions.json"),JSON.stringify(revisions.slice(-40),null,2))}
function ensureElements(project:CreativeProject){for(const scene of project.scenes)if(!scene.elements?.length)scene.elements=defaultSceneElements(project,scene.id);return project}
async function jobExists(id:string){return process.env.VERCEL?await getRemoteVideoJob(id):await getVideoJob(id)}

export async function GET(_request:Request,context:{params:Promise<{id:string}>}){const {id}=await context.params;if(!await jobExists(id))return NextResponse.json({detail:"Video job not found."},{status:404});const project=await readProject(id);if(!project)return NextResponse.json({detail:"CreativeProject has not been generated yet."},{status:404});const revisions=await readRevisions(id);return NextResponse.json({project:ensureElements(project),revisions:revisions.map(({project:_,...revision})=>revision),findings:validateEditableProject(project)},{headers:{"cache-control":"no-store"}})}

export async function POST(request:Request,context:{params:Promise<{id:string}>}){const {id}=await context.params;const body=await request.json().catch(()=>null) as {baseVersion?:number;commands?:EditorCommand[];userId?:string}|null;if(!body||!Array.isArray(body.commands)||body.commands.length<1||body.commands.length>100)return NextResponse.json({detail:"A command batch is required."},{status:422});const current=await readProject(id);if(!current)return NextResponse.json({detail:"CreativeProject was not found."},{status:404});ensureElements(current);if(body.baseVersion!==current.version)return NextResponse.json({detail:"The project changed in another session.",currentVersion:current.version},{status:409});try{const result=applyEditorCommands(current,body.commands,{...(body.userId?{userId:body.userId}:{})});const revisions=await readRevisions(id);revisions.push({id:`rev-${result.project.version}`,version:result.project.version,createdAt:result.project.updatedAt,summary:[...new Set(body.commands.map(command=>command.type))].join(", "),project:structuredClone(result.project)});await save(id,result.project,revisions);return NextResponse.json({project:result.project,revision:revisions.at(-1),audit:result.audit,findings:result.findings})}catch(error){return NextResponse.json({detail:error instanceof Error?error.message:"Command batch failed."},{status:422})}}

export async function PUT(request:Request,context:{params:Promise<{id:string}>}){const {id}=await context.params;const body=await request.json().catch(()=>null) as {revisionId?:string}|null;const revisions=await readRevisions(id);const target=revisions.find(item=>item.id===body?.revisionId);if(!target)return NextResponse.json({detail:"Revision was not found."},{status:404});const restored=structuredClone(target.project);restored.version=Math.max(...revisions.map(item=>item.version),restored.version)+1;restored.updatedAt=new Date().toISOString();restored.history.push({revision:restored.version,timestamp:restored.updatedAt,actor:"user",action:"revision-restored",changes:[target.id]});revisions.push({id:`rev-${restored.version}`,version:restored.version,createdAt:restored.updatedAt,summary:`Restored ${target.id}`,project:structuredClone(restored)});await save(id,restored,revisions);return NextResponse.json({project:restored,revision:revisions.at(-1)})}
