import { describe,expect,it } from "vitest";
import { createVisualBrief, validateVideoPlan } from "../../../../scripts/video-quality";
import { splitScript } from "../../../../scripts/script-scenes";

describe("UK property grounding",()=>{
 it("grounds a Victorian rear extension in required UK concepts",()=>{const brief=createVisualBrief("Before drawings, check the planning route for a Victorian rear extension.",0);expect(brief.country).toBe("United Kingdom");expect(brief.requiredVisualTerms.join(" ")).toMatch(/Victorian/i);expect(brief.requiredVisualTerms.join(" ")).toMatch(/rear extension/i);expect(brief.searchQuery).toMatch(/United Kingdom/i);});
 it("forbids common irrelevant architecture and footage",()=>{const brief=createVisualBrief("Plan a Victorian rear extension.",0);expect(brief.forbiddenVisualTerms.join(" ")).toMatch(/American suburb/i);expect(brief.forbiddenVisualTerms.join(" ")).toMatch(/skyscraper/i);expect(brief.forbiddenVisualTerms.join(" ")).toMatch(/restaurant/i);});
 it("accepts a line-matched HyperFrames UK motion visual when stock is throttled",()=>{const text="Plan a Victorian rear extension";const report=validateVideoPlan([{text,headline:text,start:0,duration:3.2,kind:"property",brief:createVisualBrief(text,0),motionVisual:"victorian-rear-extension",visualFailure:"Stock provider HTTP 429"}]);expect(report.passed).toBe(true);expect(report.scenes[0]?.visualMatchScore).toBeGreaterThanOrEqual(.9);expect(report.scenes[0]?.qualityScore).toBeGreaterThanOrEqual(.9);});
 it("keeps narration in meaningful beats and removes stray quote scenes",()=>{const beats=splitScript('"Mature oak tree located close to the proposed extension can affect foundation design. Tree roots influence soil moisture, particularly in shrinkable clay soils, causing movement during dry periods and when wet."');expect(beats.length).toBeLessThanOrEqual(5);expect(beats.every(beat=>beat.split(/\s+/).length>=3)).toBe(true);expect(beats.join(" ")).not.toContain('"');});
 it("allows repeated semantic motion topics while rejecting irrelevant motion",()=>{const make=(text:string,index:number,duration=3)=>({text,headline:text,start:index*3,duration,kind:"property" as const,brief:createVisualBrief(text,index),motionVisual:"tree-risk" as const});const irrelevant=validateVideoPlan([make("Review the planning drawings",0)]);expect(irrelevant.passed).toBe(false);const related=validateVideoPlan([make("Oak tree roots",0),make("Tree roots near the house",1),make("Mature oak tree",2,5.2)]);expect(related.passed).toBe(true);});
 it("accepts a long photographic image-motion property scene",()=>{const text="A Victorian property exterior";const report=validateVideoPlan([{text,headline:text,start:0,duration:5.2,kind:"property",brief:createVisualBrief(text,0),visualAsset:"house.jpg"}]);expect(report.scenes[0]?.failures.join(" ")).not.toMatch(/Static scene exceeds/i);});
});
