import type { CreateVideoJobInput, VideoJobStatus } from "@openvideo/contracts";

export type VideoJob = {
  id: string;
  input: CreateVideoJobInput;
  status: VideoJobStatus;
  progress: number;
  stage: string;
  createdAt: string;
  updatedAt: string;
  outputUrl?: string;
  canvaUrl?: string;
  generationId: string;
  variationSeed: string;
  projectId: string;
  creativeFingerprint?: string;
  inspectorUrl?: string;
  creativeProjectUrl?: string;
  creativeProjectVersion?: number;
  canvaDesignId?: string;
  canvaEditUrl?: string;
  attempt?: number;
  maxAttempts?: number;
  recoveryMode?: "standard" | "safe-assets";
  cancelTokenHash?: string;
  cancelledAt?: string;
  qualityScore?: number;
  qualityStatus?: "passed";
  qualityWarnings?: number;
  longFormPlan?: Array<{
    scene: number;
    narration: string;
    durationSeconds: number;
    visualSource: "slide" | "drive-footage" | "premium-fallback" | "pending";
    slide?: number;
    semanticScore?: number;
    captionLane: "upper" | "lower";
    status: "planned" | "prepared" | "rendered";
  }>;
  chapterProgress?: { completed: number; total: number; current?: number };
  error?: { code: string; message: string };
};
