"use client";
import {useCallback,useEffect,useRef,useState,type ComponentType,type Dispatch,type SetStateAction} from "react";
import {applyEditorCommands} from "@openvideo/creative-project/commands";
import type {CreativeProject,EditableElement,EditorCommand,CaptionPhrase} from "@openvideo/creative-project";
import {AlignCenter,ArrowDown,ArrowUp,Box,ChevronLeft,Clock3,Copy,Download,Film,History,Image,Layers3,Lock,Music2,Pause,Play,Redo2,Save,Shapes,Subtitles,Text,Trash2,Undo2,Unlock,Upload,ZoomIn} from "lucide-react";

declare const require:(id:string)=>unknown;
const Player=(require("@remotion/player") as {Player:ComponentType<Record<string,unknown>>}).Player;
const PlandomeScene=(require("@openvideo/remotion-renderer/player") as {PlandomeScene:ComponentType<Record<string,unknown>>}).PlandomeScene;
type PlayerHandle={toggle:()=>void;isPlaying:()=>boolean;seekTo:(frame:number)=>void};

type Revision={id:string;version:number;createdAt:string;summary:string;renderArtifact?:string};
type SaveState="Saved"|"Saving"|"Unsaved changes"|"Save failed"|"Conflict detected";
const variation={version:"1.0",seed:"editor",dominantVisualFamily:"editorial-property",templateSequence:[],layoutSequence:[],textAlignmentSequence:["left"],headlineTreatmentSequence:["editorial"],mediaFramingStrategy:"full bleed",imageMaskSequence:["none"],cameraSequence:["push"],transitionSequence:["crossfade"],captionTreatment:"phrase",overlayDensity:.65,motionIntensity:.5,pacingProfile:"balanced",typographyScale:1,ctaTreatment:"branded",safeZoneProfile:"vertical",assetDiversityRules:{maximumRepeats:2,minimumUniqueRatio:.65}};
const tabs=[[Layers3,"Scenes"],[Image,"Media"],[Text,"Text"],[Music2,"Audio"]] as const;
function Preview({scene,media,logo}:{scene:CreativeProject["scenes"][number];media?:string;logo:string}){return <PlandomeScene scene={scene} {...(media?{media}:{})} logo={logo} layout="full-bleed" variation={variation} sceneIndex={scene.order}/>}
const assetFor=(project:CreativeProject,sceneId:string)=>{const scene=project.scenes.find(s=>s.id===sceneId);return project.assets.find(a=>a.assetId===scene?.selectedAssetId)?.uri};
const recoveryKey=(id:string)=>`plandome-editor-recovery:${id}`;

export function CreativeVideoEditor({projectId}:{projectId:string}){
 const [project,setProject]=useState<CreativeProject>();const [revisions,setRevisions]=useState<Revision[]>([]);const [sceneId,setSceneId]=useState("");const [elementId,setElementId]=useState("");const [tab,setTab]=useState("Scenes");const [saveState,setSaveState]=useState<SaveState>("Saved");const [pending,setPending]=useState<EditorCommand[]>([]);const [undo,setUndo]=useState<CreativeProject[]>([]);const [redo,setRedo]=useState<CreativeProject[]>([]);const [historyOpen,setHistoryOpen]=useState(false);const [safeZones,setSafeZones]=useState(true);const [zoom,setZoom]=useState(.54);const [playhead,setPlayhead]=useState(0);const player=useRef<PlayerHandle>(null);const drag=useRef<{x:number;y:number;box:EditableElement["box"]}|null>(null);const saving=useRef(false);
 const scene=project?.scenes.find(s=>s.id===sceneId)??project?.scenes[0];const element=scene?.elements?.find(e=>e.id===elementId);const duration=project?.brief.durationSeconds??1;const dimensions=project?.brief.aspectRatio==="16:9"?{w:960,h:540}:project?.brief.aspectRatio==="1:1"?{w:720,h:720}:{w:405,h:720};
 const load=useCallback(async()=>{const response=await fetch(`/api/v1/video-jobs/${projectId}/editor`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Project could not be loaded.");const recovered=localStorage.getItem(recoveryKey(projectId));const next=recovered?JSON.parse(recovered) as CreativeProject:body.project as CreativeProject;setProject(next);setRevisions(body.revisions);setSceneId(next.scenes[0]?.id??"");setElementId(next.scenes[0]?.elements?.find(e=>e.role==="headline")?.id??"");if(recovered)setSaveState("Unsaved changes")},[projectId]);
 useEffect(()=>{void load()},[load]);
 const commit=useCallback((command:EditorCommand,mutate:(draft:CreativeProject)=>void)=>{if(!project)return;setUndo(stack=>[...stack.slice(-49),structuredClone(project)]);setRedo([]);const next=structuredClone(project);mutate(next);setProject(next);setPending(commands=>[...commands,command]);setSaveState("Unsaved changes");localStorage.setItem(recoveryKey(projectId),JSON.stringify(next))},[project,projectId]);
 const save=useCallback(async()=>{if(!project||!pending.length||saving.current)return;const batch=pending;saving.current=true;setSaveState("Saving");try{const response=await fetch(`/api/v1/video-jobs/${projectId}/editor`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({baseVersion:project.version,commands:batch})});const body=await response.json();if(response.status===409){setSaveState("Conflict detected");return}if(!response.ok)throw new Error(body.detail);setPending(current=>{const remaining=current.slice(batch.length);const next=remaining.length?applyEditorCommands(body.project,remaining).project:body.project;next.version=body.project.version;setProject(next);setSaveState(remaining.length?"Unsaved changes":"Saved");if(!remaining.length)localStorage.removeItem(recoveryKey(projectId));return remaining});setRevisions(current=>[...current,body.revision])}catch{setSaveState("Save failed")}finally{saving.current=false}},[pending,project,projectId]);
 useEffect(()=>{if(!pending.length)return;const timer=setTimeout(()=>void save(),900);return()=>clearTimeout(timer)},[pending,save]);
 useEffect(()=>{const keys=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();if(event.shiftKey)redoOnce();else undoOnce()}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="d"&&element){event.preventDefault();duplicate()}if((event.key==="Delete"||event.key==="Backspace")&&element&&!element.locked&&(event.target as HTMLElement).tagName!=="INPUT"&&(event.target as HTMLElement).tagName!=="TEXTAREA"){event.preventDefault();remove()}if(event.key==="Escape")setElementId("")};window.addEventListener("keydown",keys);return()=>window.removeEventListener("keydown",keys)});
 function applySnapshot(next:CreativeProject,to:Dispatch<SetStateAction<CreativeProject[]>>){if(!project)return;to(stack=>[...stack,structuredClone(project)]);setProject(next);setPending([]);setSaveState("Unsaved changes");localStorage.setItem(recoveryKey(projectId),JSON.stringify(next))}
 function undoOnce(){const next=undo.at(-1);if(next){setUndo(s=>s.slice(0,-1));applySnapshot(next,setRedo)}}function redoOnce(){const next=redo.at(-1);if(next){setRedo(s=>s.slice(0,-1));applySnapshot(next,setUndo)}}
 function updateElement(command:EditorCommand,change:(e:EditableElement)=>void){if(!scene||!element||element.locked)return;commit(command,draft=>{const target=draft.scenes.find(s=>s.id===scene.id)?.elements?.find(e=>e.id===element.id);if(target)change(target)})}
 function duplicate(){if(!scene||!element)return;const clone={...structuredClone(element),id:`${element.id}-${Date.now()}`,name:`${element.name} copy`,box:{...element.box,x:Math.min(.9,element.box.x+.02),y:Math.min(.9,element.box.y+.02)}};commit({type:"DuplicateElement",sceneId:scene.id,elementId:element.id,newId:clone.id},draft=>draft.scenes.find(s=>s.id===scene.id)?.elements?.push(clone));setElementId(clone.id)}
 function remove(){if(!scene||!element||element.locked)return;commit({type:"DeleteElement",sceneId:scene.id,elementId:element.id},draft=>{const target=draft.scenes.find(s=>s.id===scene.id);if(target)target.elements=(target.elements??[]).filter(e=>e.id!==element.id)});setElementId("")}
 function reorder(direction:-1|1){if(!project||!scene)return;const index=project.scenes.findIndex(s=>s.id===scene.id),to=Math.max(0,Math.min(project.scenes.length-1,index+direction));commit({type:"ReorderScene",sceneId:scene.id,toIndex:to},draft=>{const at=draft.scenes.findIndex(s=>s.id===scene.id);const [item]=draft.scenes.splice(at,1);if(item)draft.scenes.splice(to,0,item);draft.scenes.forEach((s,i)=>s.order=i)})}
 async function restore(id:string){const response=await fetch(`/api/v1/video-jobs/${projectId}/editor`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({revisionId:id})});const body=await response.json();if(response.ok){setProject(body.project);setPending([]);setSaveState("Saved");setHistoryOpen(false)}}
 function pointerDown(event:React.PointerEvent){if(!element||element.locked)return;(event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);drag.current={x:event.clientX,y:event.clientY,box:structuredClone(element.box)}}
 function pointerMove(event:React.PointerEvent){if(!drag.current||!element||!scene||!project)return;const scale=Math.min(dimensions.w/(dimensions.w),dimensions.h/(dimensions.h));const x=Math.max(0,Math.min(1-element.box.width,drag.current.box.x+(event.clientX-drag.current.x)/(dimensions.w*zoom/scale)));const y=Math.max(0,Math.min(1-element.box.height,drag.current.box.y+(event.clientY-drag.current.y)/(dimensions.h*zoom/scale)));setProject(current=>{if(!current)return current;const next=structuredClone(current);const e=next.scenes.find(s=>s.id===scene.id)?.elements?.find(e=>e.id===element.id);if(e){e.box.x=x;e.box.y=y}return next})}
 function pointerUp(){if(!drag.current||!element||!scene)return;drag.current=null;updateElement({type:"MoveElement",sceneId:scene.id,elementId:element.id,x:element.box.x,y:element.box.y},()=>{})}
 if(!project||!scene)return <div className="creative-editor-loading">Loading editable CreativeProject…</div>;
 const media=assetFor(project,scene.id);const frames=Math.max(1,Math.round(scene.duration*project.rendering.fps));const tracks=[{label:"Scenes",clips:project.timeline.filter(c=>c.track==="video")},{label:"Captions",clips:project.timeline.filter(c=>c.track==="caption")},{label:"Narration",clips:project.timeline.filter(c=>c.track==="narration")},{label:"Music",clips:project.timeline.filter(c=>c.track==="music")}];
 return <div className="creative-editor">
  <header className="creative-topbar"><div className="creative-title"><button aria-label="Back"><ChevronLeft/></button><Film/><div><strong>{project.brief.brand} video</strong><small>{project.id} · revision {project.version}</small></div></div><div className={`save-pill save-${saveState.replaceAll(" ","-").toLowerCase()}`}>{saveState}</div><div className="creative-actions"><button onClick={undoOnce} disabled={!undo.length}><Undo2/> Undo</button><button onClick={redoOnce} disabled={!redo.length}><Redo2/> Redo</button><button onClick={()=>setHistoryOpen(true)}><History/> History</button><select value={project.brief.aspectRatio} onChange={e=>setProject({...project,brief:{...project.brief,aspectRatio:e.target.value as CreativeProject["brief"]["aspectRatio"]}})}><option>9:16</option><option>1:1</option><option>16:9</option></select><span className="renderer-chip">{project.rendering.engine}</span><button className="primary" onClick={()=>void save()}><Save/> Save</button><a href={`/api/v1/video-jobs/${projectId}/download`}><Download/> Render</a></div></header>
  <div className="creative-workspace"><nav className="creative-rail">{tabs.map(([Icon,label])=><button key={label} className={tab===label?"active":""} onClick={()=>setTab(label)}><Icon/><span>{label}</span></button>)}</nav>
   <aside className="creative-library"><h2>{tab}</h2>{tab==="Scenes"&&<div className="scene-list">{project.scenes.map((s,i)=><button key={s.id} className={s.id===scene.id?"active":""} onClick={()=>{setSceneId(s.id);setElementId(s.elements?.find(e=>e.role==="headline")?.id??"")}}><i>{i+1}</i><span><strong>{s.headline}</strong><small>{s.duration.toFixed(1)} sec · {s.templateId}</small></span></button>)}</div>}{tab==="Templates"&&<div className="template-grid">{project.templates.map(t=><button key={t.id} onClick={()=>commit({type:"ChangeSceneTemplate",sceneId:scene.id,templateId:t.id},draft=>{const s=draft.scenes.find(x=>x.id===scene.id);if(s)s.templateId=t.id})}><Box/><strong>{t.name}</strong><small>{t.capabilities.preferredDuration.join("–")}s</small></button>)}</div>}{tab==="Text"&&<button className="library-add" onClick={()=>setElementId(scene.elements?.find(e=>e.role==="headline")?.id??"")}><Text/> Edit headline</button>}{tab==="Media"&&<div className="asset-list">{project.assets.filter(a=>a.mediaType!=="audio").map(a=><button key={a.assetId} onClick={()=>{const target=scene.elements?.find(e=>e.type==="image"||e.type==="video");if(target){setElementId(target.id);updateElement({type:"ReplaceAsset",sceneId:scene.id,elementId:target.id,assetId:a.assetId},e=>e.assetId=a.assetId)}}}><Image/><span>{a.reason}</span></button>)}</div>}{tab==="Audio"&&<div className="library-form"><label>Narration LUFS<input type="number" defaultValue={project.audio.narration.loudnessTargetLufs} onBlur={e=>commit({type:"UpdateAudioMix",narrationLufs:Number(e.target.value)},d=>d.audio.narration.loudnessTargetLufs=Number(e.target.value))}/></label><label>Music dB<input type="number" defaultValue={project.audio.music.levelDb} onBlur={e=>commit({type:"UpdateAudioMix",musicLevelDb:Number(e.target.value)},d=>d.audio.music.levelDb=Number(e.target.value))}/></label><label>Ducking dB<input type="number" defaultValue={project.audio.music.duckingDb} onBlur={e=>commit({type:"UpdateAudioMix",duckingDb:Number(e.target.value)},d=>d.audio.music.duckingDb=Number(e.target.value))}/></label></div>}</aside>
   <main className="creative-stage-column"><div className="stage-toolbar"><button onClick={()=>setSafeZones(!safeZones)}>Safe zones {safeZones?"on":"off"}</button><span/><button onClick={()=>setZoom(Math.max(.3,zoom-.1))}>−</button><button><ZoomIn/> {Math.round(zoom*100)}%</button><button onClick={()=>setZoom(Math.min(1,zoom+.1))}>+</button></div><div className="creative-stage"><div className="player-frame" style={{width:dimensions.w*zoom,height:dimensions.h*zoom}}><Player ref={player} component={Preview} inputProps={{scene,...(media?{media}:{}),logo:"/brand/plandome-logo.png"}} durationInFrames={frames} compositionWidth={project.rendering.width} compositionHeight={project.rendering.height} fps={project.rendering.fps} controls={false} style={{width:"100%",height:"100%"}}/>{safeZones&&<div className="safe-zone"/>}{scene.elements?.map(e=>e.visible&&<button key={e.id} className={`element-hitbox ${e.id===elementId?"selected":""} ${e.locked?"locked":""}`} style={{left:`${e.box.x*100}%`,top:`${e.box.y*100}%`,width:`${e.box.width*100}%`,height:`${e.box.height*100}%`,zIndex:e.layer}} onClick={()=>setElementId(e.id)} onDoubleClick={()=>e.type==="text"&&setTab("Text")} onPointerDown={e.id===elementId?pointerDown:undefined} onPointerMove={e.id===elementId?pointerMove:undefined} onPointerUp={e.id===elementId?pointerUp:undefined} aria-label={`Select ${e.name}`}>{e.id===elementId&&<><i className="handle nw"/><i className="handle ne"/><i className="handle sw"/><i className="handle se"/></>}</button>)}</div></div><div className="transport"><button onClick={()=>player.current?.toggle()}>{player.current?.isPlaying()?<Pause/>:<Play/>}</button><strong>{playhead.toFixed(1)}s</strong><input type="range" min={scene.start} max={scene.start+scene.duration} step={1/project.rendering.fps} value={playhead} onChange={e=>{const value=Number(e.target.value);setPlayhead(value);player.current?.seekTo(Math.round((value-scene.start)*project.rendering.fps))}}/><span>{duration.toFixed(1)}s</span></div>
    <div className="multi-timeline"><div className="timeline-ruler"><Clock3/><span style={{left:`${playhead/duration*100}%`}}/></div>{tracks.map(({label,clips})=><div className="track" key={label}><b>{label}</b><div>{clips.map(clip=><button key={clip.id} className={clip.sceneId===scene.id?"active":""} style={{left:`${clip.start/duration*100}%`,width:`${clip.duration/duration*100}%`}} onClick={()=>clip.sceneId&&setSceneId(clip.sceneId)}>{clip.sceneId?.replace("scene-","")??label}</button>)}</div></div>)}</div></main>
   <aside className="creative-inspector"><div className="inspector-head"><div><strong>{element?.name??"Scene"}</strong><small>{element?"Element properties":"Scene properties"}</small></div>{element&&<div><button onClick={duplicate}><Copy/></button><button onClick={()=>updateElement({type:"LockElement",sceneId:scene.id,elementId:element.id,locked:!element.locked},e=>e.locked=!e.locked)}>{element.locked?<Lock/>:<Unlock/>}</button><button onClick={remove} disabled={element.locked}><Trash2/></button></div>}</div>{element?<ElementInspector element={element} sceneId={scene.id} update={updateElement}/>:<SceneInspector project={project} scene={scene} commit={commit} reorder={reorder}/>}<CaptionEditor captions={project.captions.filter(c=>c.sceneId===scene.id)} commit={commit}/></aside>
  </div>{historyOpen&&<div className="revision-modal"><section><header><h2>Revision history</h2><button onClick={()=>setHistoryOpen(false)}>×</button></header>{revisions.toReversed().map(r=><article key={r.id}><div><strong>Revision {r.version}</strong><small>{new Date(r.createdAt).toLocaleString()}</small><p>{r.summary}</p></div><button onClick={()=>void restore(r.id)}>Restore</button></article>)}</section></div>}</div>
}

function ElementInspector({element,sceneId,update}:{element:EditableElement;sceneId:string;update:(c:EditorCommand,m:(e:EditableElement)=>void)=>void}){return <div className="inspector-form">{element.type==="text"&&<><label>Text<textarea value={element.content??""} onChange={e=>update({type:"UpdateTextContent",sceneId,elementId:element.id,content:e.target.value},x=>x.content=e.target.value)}/></label><label>Font<select value={element.style.fontFamily} onChange={e=>update({type:"UpdateElementStyle",sceneId,elementId:element.id,style:{fontFamily:e.target.value}},x=>x.style.fontFamily=e.target.value)}><option>Montserrat</option><option>Arial</option></select></label><label>Font size<input type="number" value={element.style.fontSize??72} onChange={e=>update({type:"UpdateElementStyle",sceneId,elementId:element.id,style:{fontSize:Number(e.target.value)}},x=>x.style.fontSize=Number(e.target.value))}/></label><label>Colour<input type="color" value={element.style.colour??"#ffffff"} onChange={e=>update({type:"UpdateElementStyle",sceneId,elementId:element.id,style:{colour:e.target.value}},x=>x.style.colour=e.target.value)}/></label></>}{element.media&&<><label>Crop X<input type="range" min="0" max="1" step=".01" value={element.media.crop.x} onChange={e=>update({type:"SetMediaCrop",sceneId,elementId:element.id,crop:{...element.media!.crop,x:Number(e.target.value)}},x=>x.media!.crop.x=Number(e.target.value))}/></label><label>Focal X<input type="range" min="0" max="1" step=".01" value={element.media.focalPoint.x} onChange={e=>update({type:"SetMediaFocalPoint",sceneId,elementId:element.id,focalPoint:{...element.media!.focalPoint,x:Number(e.target.value)}},x=>x.media!.focalPoint.x=Number(e.target.value))}/></label></>}<label>Layer<input type="number" value={element.layer} onChange={e=>update({type:"UpdateElementStyle",sceneId,elementId:element.id,style:{}},x=>x.layer=Number(e.target.value))}/></label><label>Animation<select value={element.animation.type} onChange={e=>update({type:"ChangeAnimation",sceneId,elementId:element.id,animation:{type:e.target.value as EditableElement["animation"]["type"]}},x=>x.animation.type=e.target.value as EditableElement["animation"]["type"])}>{["none","fade","rise","slide","scale","mask-reveal","line-reveal","document-reveal"].map(x=><option key={x}>{x}</option>)}</select></label></div>}
function SceneInspector({project,scene,commit,reorder}:{project:CreativeProject;scene:CreativeProject["scenes"][number];commit:(c:EditorCommand,m:(p:CreativeProject)=>void)=>void;reorder:(d:-1|1)=>void}){return <div className="inspector-form"><div className="row-actions"><button onClick={()=>reorder(-1)}><ArrowUp/></button><button onClick={()=>reorder(1)}><ArrowDown/></button></div><label>Duration <input type="range" min=".5" max="30" step=".25" value={scene.duration} onChange={e=>commit({type:"ChangeSceneDuration",sceneId:scene.id,duration:Number(e.target.value)},d=>{const s=d.scenes.find(x=>x.id===scene.id);if(s)s.duration=Number(e.target.value)})}/><output>{scene.duration.toFixed(2)}s</output></label><label>Transition<select value={scene.transition} onChange={e=>commit({type:"ChangeTransition",sceneId:scene.id,transition:e.target.value},d=>{const s=d.scenes.find(x=>x.id===scene.id);if(s)s.transition=e.target.value})}>{["crossfade","clean-slide","mask-reveal","subtle-zoom","document-page","comparison-wipe"].map(x=><option key={x}>{x}</option>)}</select></label><label>Renderer<select value={project.rendering.engine} onChange={e=>commit({type:"SetRenderer",engine:e.target.value as "remotion"|"hyperframes"},d=>d.rendering.engine=e.target.value as "remotion"|"hyperframes")}><option>remotion</option><option>hyperframes</option></select></label></div>}
function CaptionEditor({captions,commit}:{captions:CaptionPhrase[];commit:(c:EditorCommand,m:(p:CreativeProject)=>void)=>void}){return <details className="caption-editor"><summary><Subtitles/> Captions ({captions.length})</summary>{captions.map(c=><label key={c.id}><input value={c.text} onChange={e=>commit({type:"UpdateCaption",phraseId:c.id,text:e.target.value},d=>{const phrase=d.captions.find(x=>x.id===c.id);if(phrase)phrase.text=e.target.value})}/><small>{c.start.toFixed(1)}–{c.end.toFixed(1)}s</small></label>)}</details>}
